#spring:
#  redis:
#    host: 192.168.75.128
#    port: 6379
#    password: redis@123
#    maxIdle: 50
#    maxWaitMillis: 5000
#    maxTotal: 500
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    maxIdle: 50
    maxWaitMillis: 5000
    maxTotal: 500

server:
  port: 8080


logging:
  level:
    root: INFO
    com.boot: DEBUG  # 项目包的日志级别
    org.springframework: WARN  # Spring框架的日志级别
    org.redisson: INFO  # Redisson相关日志级别
    org.springframework.data.redis: INFO  # Redis数据访问日志级别
  config: classpath:logback.xml

