#spring:
#  redis:
#    host: 192.168.75.128
#    port: 6379
#    password: redis@123
#    maxIdle: 50
#    maxWaitMillis: 5000
#    maxTotal: 500
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    maxIdle: 50
    maxWaitMillis: 5000
    maxTotal: 500

server:
  port: 8080